#' Summarize data types for the study
#'
#' Data types are summarized, or "rolled-up", for the study based on its child file annotations.
#' This summary is added as (and will overwrite the current) `dataType` annotation for the study.
#' Contrast this with `update_study_annotations`, where study-level annotations are rolled down to child files.
#'
#' @param study_table_id Synapse ID of the portal study table/view that lists relevant studies in column `id` or `studyId`.
#' @param fileview_id Synapse ID of the portal fileview.
#' @param id_col Name of the id column in `study_table_id` and `fileview_id`.
#' @param attribute The attribute that we are rolling up; defaults to `dataType`. Must be queryable in `fileview_id`.
#' @param dry_run Default = TRUE. Skips updating the annotation and instead displays annotation object.
#' @examples
#' \dontrun{
#' assign_study_data_types(study_table_id = 'syn52677631', # either syn52677631 or syn52694652 OK
#'                         fileview_id = 'syn16858331',
#'                         id_col = 'studyId',
#'                         id_col = 'studyId',
#'                         dry_run = T)
#'}
#' @export
assign_study_data_types <- function(study_table_id,
                                    fileview_id,
                                    id_col = "studyId",
                                    attribute = "dataType",
                                    dry_run = TRUE) {

  .check_login()

  # get studies from study table
  studies <- .syn$tableQuery(glue::glue("select {id_col} from {study_table_id}", includeRowIdAndRowVersion=T))

  # query the fileview
  fv <- .syn$tableQuery(
    glue::glue('select {id_col},{attribute} from {fileview_id} where type = \'file\' and {attribute} is not null and {id_col} is not null'))$filepath %>%
    readr::read_csv(na=character()) ##asDataFrame() & reticulate return rowIdAndRowVersion as concatenated rownames, read_csv reads them in as column

  if(dry_run == FALSE){

  } else{

  }
}

#' Retrieve valid subclasses of a value in a JSON-LD schema
#' @description Retrieve valid subclasses of a value in a JSON-LD schema generated by schematic.
#' @param schema_url Default: the NF-OSI JSON-LD schema.
#' @param parent_name Default = DataType. The value for which you'd like to find the associated subclasses.
#' @param parent_context Default = bts. The JSON-LD context for the value in question.
#' @return A character vector of values.
#' @export
get_valid_values_from_json_schema <- function(schema_url = 'https://raw.githubusercontent.com/nf-osi/nf-metadata-dictionary/main/NF.jsonld',
                                              parent_name = 'DataType',
                                              parent_context = 'bts'){

  parent_id <- paste0(parent_context, ':', parent_name)

  subclasses <-
    jsonlite::fromJSON(schema_url) %>%
    purrr::pluck("@graph") %>%
    dplyr::filter(purrr::map_lgl(`rdfs:subClassOf`, ~ parent_id %in% .x)) %>%
    dplyr::pull(`sms:displayName`)

  subclasses
}
